"use client";

import { useMemo, useState } from "react";

const LOGO="https://raw.githubusercontent.com/smaislamalghozali103-byte/raport_pondok_integrasi/main/public/assets/logo-ypi-al-ghozali.png";
const subjects=[
["Tamrin Lughoh","تمرين اللغة"],["Mutholaah","المطالعة"],["Aqidah","العقيدة"],["Hadist","الحديث"],["Fiqih","الفقه"],
["Tarikh Islam","التاريخ الإسلامي"],["Tajwid","التجويد"],["Imla","الإملاء"],["Khot","الخط"],["Mahfudzot","المحفوظات"],
["Pendidikan Agama Islam","التربية الدينية الإسلامية"],["Bahasa Indonesia","اللغة الإندونيسية"],["Bahasa Inggris","اللغة الإنجليزية"],
["Matematika","الرياضيات"],["Ilmu Pengetahuan Alam","علم الطبيعة"],["Ilmu Pengetahuan Sosial","علم الاجتماع"],
["Pendidikan Kewarganegaraan","التربية الوطنية"],["Informatika","علم الحاسوب"],["Pendidikan Jasmani dan Kesehatan","الرياضة البدنية والصحية"],
["Seni Budaya","الفنون الجميلة"],["Bahasa Sunda","اللغة السوندية"]
];
const students=[
["AANISAH CELYANI","3148999544"],["ABDILLAH RAHMAN","3148999545"],["AHMAD FAHRI","3148999546"],
["ALI ZAINUDDIN","3148999547"],["AMIRUL HAKIM","3148999548"]
];
const initial={Matematika:88,Fiqih:90,"Bahasa Indonesia":87,Aqidah:92,Tajwid:84,"Bahasa Inggris":86};

function toArabicDigits(value){return String(value).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)])}
function arabicNumberWord(value){const n=Math.round(Number(value));if(!Number.isFinite(n))return "";const ones=["صفر","واحد","اثنان","ثلاثة","أربعة","خمسة","ستة","سبعة","ثمانية","تسعة"];const teens=["عشرة","أحد عشر","اثنا عشر","ثلاثة عشر","أربعة عشر","خمسة عشر","ستة عشر","سبعة عشر","ثمانية عشر","تسعة عشر"];const tens=["","","عشرون","ثلاثون","أربعون","خمسون","ستون","سبعون","ثمانون","تسعون"];if(n<10)return ones[n];if(n<20)return teens[n-10];if(n<100)return n%10===0?tens[n/10]:`${ones[n%10]} و${tens[Math.floor(n/10)]}`;if(n===100)return "مائة";return String(n)}
function pred(v){const n=Number(v);return Number.isFinite(n)?n>=90?"A":n>=80?"B":n>=70?"C":"D":"—"}
function Icon({type}){const p={home:"M3 10 12 3l9 7M5 9v12h14V9M9 21v-6h6v6",edit:"M4 20h4L19 9l-4-4L4 16v4M13 6l4 4",chart:"M5 20V10M12 20V4M19 20v-7",file:"M6 3h8l4 4v14H6zM14 3v5h5M9 13h6M9 17h6",users:"M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M16 3a4 4 0 0 1 0 8M21 21v-2a4 4 0 0 0-3-4",gear:"M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM19 13a7 7 0 0 0 0-2l2-1-2-3-2 1a7 7 0 0 0-2-1l-.5-2h-3L11 7a7 7 0 0 0-2 1L7 7 5 10l2 1a7 7 0 0 0 0 2l-2 1 2 3 2-1a7 7 0 0 0 2 1l.5 2h3l.5-2a7 7 0 0 0 2-1l2 1 2-3-2-1Z",logout:"M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-7"}[type];return <svg className="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={p}/></svg>}

export default function Home(){
 const [login,setLogin]=useState(false),[user,setUser]=useState(""),[pin,setPin]=useState(""),[err,setErr]=useState("");
 const [menu,setMenu]=useState("input"),[unit,setUnit]=useState("SMP"),[klass,setKlass]=useState("1 - A"),[subject,setSubject]=useState("Tamrin Lughoh"),[student,setStudent]=useState(0),[grades,setGrades]=useState(initial),[saved,setSaved]=useState(false);
 const current=students[student]; const nums=useMemo(()=>Object.values(grades).map(Number).filter(Number.isFinite),[grades]); const total=nums.reduce((a,b)=>a+b,0),avg=nums.length?total/nums.length:0;
 const submit=e=>{e.preventDefault();if(user.trim()&&/^\d{6,}$/.test(pin)){setLogin(true);setErr("")}else setErr("Username wajib diisi dan PIN minimal 6 digit.")};
 const setGrade=v=>{if(v===""||(/^\d{0,3}$/.test(v)&&Number(v)<=100)){setGrades(g=>({...g,[subject]:v}));setSaved(false)}};

 if(!login)return <main className="login-page"><div className="orb a"/><div className="orb b"/><section className="login-card">
   <div className="login-brand">
   <img src={LOGO} alt="Logo Pondok Modern Al-Ghozali"/>
   <h1>RAPORT <b>INTEGRASI</b></h1>
   <h2>PONDOK MODERN AL-GHOZALI</h2>
   <div className="login-guide">
    <strong>PANDUAN LOGIN</strong>
    <p><b>Guru</b> — gunakan username dan PIN yang telah diberikan.</p>
    <p><b>Wali Kelas</b> — masuk dengan akun yang telah terdaftar untuk mengakses kelas bimbingan.</p>
    <p><b>Admin</b> — gunakan akses admin untuk mengelola seluruh sistem.</p>
   </div>
 </div>
   <form className="login-form" onSubmit={submit}><div><h2>Masuk ke Sistem</h2><p>Silakan masukkan username dan PIN Anda.</p></div><label>Username<input value={user} onChange={e=>setUser(e.target.value)} placeholder="Masukkan username" autoComplete="username"/></label><label>PIN<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} type="password" inputMode="numeric" maxLength={12} placeholder="Masukkan PIN" autoComplete="current-password"/></label>{err&&<div className="error">{err}</div>}<button className="primary" type="submit"><Icon type="logout"/> Masuk</button><small className="login-help">Lupa PIN? Hubungi Admin Sistem.</small><small>TA 2026/2027 • PTS Ganjil</small></form>
 </section><footer>© 2026 Pondok Modern Al-Ghozali</footer></main>;

 return <main className="shell"><header className="topbar"><div className="brand"><img src={LOGO} alt="Logo YPI Al-Ghozali"/><div><b>RAPORT PONDOK MODERN AL-GHOZALI</b><span>TA 2026/2027 • PTS GANJIL</span></div></div><div className="account"><div className="avatar">AG</div><div><b>{user||"Demo Admin"}</b><span>Administrator</span></div><button onClick={()=>setLogin(false)}>Keluar</button></div></header>
 <div className="layout"><aside className="sidebar"><span className="menu-title">MENU UTAMA</span>{[["input","Input Nilai","edit"],["rekap","Rekap Nilai","chart"],["raport","Raport Web","file"],["master","Master Data","users"]].map(x=><button key={x[0]} className={menu===x[0]?"nav active":"nav"} onClick={()=>setMenu(x[0])}><Icon type={x[2]}/>{x[1]}</button>)}<span className="menu-title mt">SISTEM</span><button className={menu==="setting"?"nav active":"nav"} onClick={()=>setMenu("setting")}><Icon type="gear"/>Pengaturan</button><div className="safe"><b>● Mode aman</b><span>Nilai tidak disimpan di Local Storage.</span></div><small className="ver">AL-GHOZALI WEB • UI v2.0</small></aside>
 <section className="content"><div className="heading"><div><span>Beranda / {({input:"Input Nilai",rekap:"Rekap Nilai",raport:"Raport Web",master:"Master Data",setting:"Pengaturan"})[menu]}</span><h2>{({input:"Input Nilai Siswa",rekap:"Rekap Nilai",raport:"Raport Web",master:"Master Data",setting:"Pengaturan"})[menu]}</h2><p>Panel hanya menampilkan fungsi yang sedang dipilih.</p></div><div className="actions">{menu==="raport"&&<button className="outline" onClick={()=>window.print()}>⤓ Cetak PDF</button>}{menu==="input"&&<button className="primary compact" onClick={()=>setSaved(true)}>✓ Simpan Nilai</button>}</div></div>
 {menu==="input"&&<>
 <div className="module-card">
  <div className="module-title"><div><span className="module-kicker">INPUT NILAI</span><h3>Pilih konteks penilaian</h3><p>Filter tampil di dalam panel ini dan tidak memenuhi halaman ketika fungsi lain dipilih.</p></div></div>
  <div className="filter-grid"><label>Tahun Ajaran<select><option>2026/2027 — Ganjil</option></select></label><label>Jenjang<select value={unit} onChange={e=>setUnit(e.target.value)}><option>SMP</option><option>SMA</option><option>TMMIA</option></select></label><label>Kelas<select value={klass} onChange={e=>setKlass(e.target.value)}><option>1 - A</option><option>1 - B</option><option>2 - A</option><option>3 - A</option></select></label><label>Mata Pelajaran<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s[0]}>{s[0]}</option>)}</select></label></div>
 </div>
 <section className="card module-card"><div className="card-head"><div><h3>Input Nilai</h3><p>{subject} • {klass} • {unit}</p></div><span className="pill">{saved?"Tersimpan (demo)":"Belum disimpan"}</span></div><div className="table-scroll"><table><thead><tr><th>No</th><th>NISN</th><th>Nama Siswa</th><th>Kelas</th><th>Nilai</th><th>Predikat</th></tr></thead><tbody>{students.map((s,i)=>{let v=i===0?(grades[subject]??""):[86,88,90,84][i-1];return <tr className={i===student?"selected":""} key={s[1]}><td>{i+1}</td><td>{s[1]}</td><td><button className="student" onClick={()=>setStudent(i)}>{s[0]}</button></td><td>{klass}</td><td><input value={v} disabled={i!==0} onChange={e=>setGrade(e.target.value)}/></td><td><em className={"badge "+pred(v).toLowerCase()}>{pred(v)}</em></td></tr>})}</tbody></table></div><div className="foot">Menampilkan 5 siswa • demo UI <button>Lihat semua siswa →</button></div></section>
 </>}
 {menu==="rekap"&&<section className="card module-card"><div className="card-head"><div><h3>Rekap Nilai</h3><p>Ringkasan progres input berdasarkan data yang nanti berasal dari Apps Script.</p></div></div><div className="stats compact-stats">{[["617","Jumlah Siswa","Siswa aktif","green"],["124","Jumlah Guru","Guru aktif","gold"],["63","Jumlah Mapel","Mata pelajaran","blue"],["84%","Input Hari Ini","Progress nilai","purple"]].map(x=><div className="stat" key={x[1]}><i className={x[3]}>{x[0]==="84%"?"✓":"◆"}</i><div><span>{x[1]}</span><b>{x[0]}</b><small>{x[2]}</small></div></div>)}</div><div className="table-scroll"><table><thead><tr><th>Jenjang</th><th>Kelas</th><th>Mata Pelajaran</th><th>Guru</th><th>Status</th></tr></thead><tbody><tr><td>SMP</td><td>{klass}</td><td>{subject}</td><td>Belum terhubung</td><td><em className="badge b">Menunggu Apps Script</em></td></tr></tbody></table></div></section>}
 {menu==="raport"&&<aside className="card preview module-card"><div className="card-head"><div><h3>Preview Raport</h3><p>Render web • bukan tampilan Excel</p></div><button className="tiny" onClick={()=>window.print()}>Cetak</button></div><article className="report"><div className="rhead"><img src={LOGO} alt="Logo"/><div><h1>كشف الدرجات</h1><p>للامتحان التّحريري لمنتصف الفصل الدّراسي الأوّل</p></div><img src={LOGO} alt="Logo"/></div><div className="identity"><span><b>الاسم كامل :</b> {current[0]}</span><span><b>الصّفّ :</b> {klass==="1 - A"?"الأوّل - A":klass==="1 - B"?"الأوّل - B":klass==="2 - A"?"الثّاني - A":klass==="3 - A"?"الثّالث - A":klass}</span><span><b>الرقم :</b> {current[1]}</span><span><b>العام الدّراسي :</b> ٢۰۲٧ / ٢۰۲٦</span></div><table className="report-table"><thead><tr><th colSpan="3">الدّرجة الّتي حصلت عليها الطالب / الطالبة</th><th>Mata Pelajaran</th><th>المواد الدّراسيّة</th><th className="report-no-head">الرقم</th></tr></thead><tbody>{subjects.map((s,i)=>{let v=Number(grades[s[0]]);let value=Number.isFinite(v)?v:0;return <tr key={s[0]}><td className="grade-word">{arabicNumberWord(value)}</td><td className="grade-western">{Number.isFinite(v)?v:""}</td><td className="grade-arabic">{Number.isFinite(v)?toArabicDigits(v):""}</td><td className="subject-id">{s[0]}</td><td className="subject-ar" dir="rtl">{s[1]}</td><td className="arabic-no">{toArabicDigits(i+1)}</td></tr>})}<tr className="sum"><td></td><td>{nums.length?total:""}</td><td>{nums.length?toArabicDigits(total):""}</td><td>Jumlah</td><td dir="rtl">المجـموع</td><td></td></tr><tr className="sum"><td></td><td>{nums.length?avg.toFixed(2):""}</td><td>{nums.length?toArabicDigits(avg.toFixed(2)):""}</td><td>Nilai Rata Rata</td><td dir="rtl">النتيجـة المـعدّلة</td><td></td></tr><tr className="sum"><td>الأول</td><td>1</td><td>١</td><td>Peringkat</td><td dir="rtl">المقام</td><td></td></tr></tbody></table><div className="date">تحريرا بغونونج سندور، ۱۰ اكتوبار ٢۰۲٦/ ٢٧ ربيع الآخر ۱٤٤۸</div><div className="sign"><div><b>ولي الأمر</b><span className="sign-line"></span><small>________________</small></div><div><b>ولي الفصل</b><span className="sign-line"></span><small>Amalia Nur Fariha, S.Pd</small></div><div><b>مـدير المـعهد</b><span className="sign-line"></span><small>M. Ya'qub Unang, S.Ag</small></div></div></article></aside>}
 {menu==="master"&&<section className="card module-card"><div className="card-head"><div><h3>Master Data</h3><p>Ringkasan struktur master. Detail akan dibatasi sesuai peran pengguna setelah Apps Script aktif.</p></div></div><div className="stats compact-stats">{[["617","Master Siswa","Data siswa aktif","green"],["124","Master Guru","Data guru aktif","gold"],["63","Master Mapel","Kode mata pelajaran","blue"],["9","Master Kelas","Kelompok kelas","purple"]].map(x=><div className="stat" key={x[1]}><i className={x[3]}>{x[0]==="9"?"◆":"●"}</i><div><span>{x[1]}</span><b>{x[0]}</b><small>{x[2]}</small></div></div>)}</div></section>}
 {menu==="setting"&&<section className="card module-card"><div className="card-head"><div><h3>Pengaturan</h3><p>Konfigurasi sistem akan dikelola setelah backend Apps Script dihubungkan.</p></div></div><div className="settings-grid"><div className="safe"><b>● Mode aman</b><span>Nilai tidak disimpan di Local Storage.</span></div><div className="safe"><b>● Sumber data</b><span>Google Spreadsheet melalui Apps Script.</span></div><div className="safe"><b>● Akses</b><span>Guru, Wali Kelas, dan Admin akan dibatasi berdasarkan peran.</span></div></div></section>}</section></div></main>;
}
